### ISSUE TITLE
Calculate "signup velocity" per event

### ISSUE THREAD

**Issue by heddendorp** [esn-tumi/app#154]
It would be interesting to see how long it takes for 50, 75, 90, 95, 100 percent of the spots in an event to fill up and a measurement for a 75% signup velocity could be interesting.
Such as x seconds per spot until >75% are full.

**Comment by jacbz** [comment]
Show number of people viewing event, a few minutes before registration starts

**Comment by heddendorp** [comment]
Fixed in a6e499fe6eb72d5b8c871d578556f2b5c2a0b46b
