### ISSUE TITLE
Button to sync events with template

### ISSUE THREAD

**Issue by jacbz** [esn-tumi/app#49]
There should be a "Sync" button on the event edit page.

Clicking this button opens a dialog, where you can see information of the event side-by-side with information of the template:
* Public event description
* Info for registered users
* Info for organizers

You should be able to select which information you want to copy to the template.

On the event template page, there should be a button to sync information to all future events.

**Comment by heddendorp** [comment]
Probably solving the issue of template discipline in a suboptimal way
