### ISSUE TITLE
Click on navigation bar propagates to the calendar view (mobile)

### ISSUE THREAD

**Issue by ZuzkaU** [esn-tumi/app#529]
**Describe the bug**
In mobile view of the events page, if you click on the navigation bar, the click propagates to the calendar beneath it, and a view of events for the day opens, instead of the page you clicked at the navigation bar.

**Comment by ZuzkaU** [comment]
Not anymore? Probably fixed somewhere recently.

**Comment by heddendorp** [comment]
I fixed it in d211ab5d615d11f1786dc64e475fd5d00f61b03f @ZuzkaU
