### ISSUE TITLE
Event Description Page not Loading

### ISSUE THREAD

**Issue by SamAr012** [esn-tumi/app#545]
Event description page not loading when user is not logged in. Stuck in loading.

To reproduce:
1. Log out
2. Try to access an Event description page through the calendar

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy A52s
- OS: Android Version 12, One UI 4.1
- Browser: Default Samsung browser

**Comment by heddendorp** [comment]
Fixed in 8ae984bc7868d4f4544ef3fe0f17be6dc33d107c
